dat <- read.csv('~/Desktop/Lab/Experiment/DataAnalysis/BehaviorDataAnalysis/dataSetEEG.csv', header = TRUE)
# dat <- read.csv('~/DataAnalysis/BehaviorDataAnalysis/dataSetEEG.csv', header = TRUE)
library(lme4) # library for linear regression modeling
library(car) 
m <- lmer(EEG_ITC ~ Conditions + FM_avg + ITD_avg + (1|Subject), data = dat)
m1<- lmer(EEG_ITC ~ Conditions + (1|Subject), data = dat)
anova(m, m1) # it shows which model is better, the model listed at the bottom is the best

str(dat)
dat$Conditions <- as.factor(dat$Conditions)
m <- lmer(EEG_ITC ~ Conditions + ITD_avg + Conditions:ITD_avg + (1|Subject), data = dat)
Anova(m, test.statistic = 'F')
library(ggplot2)
p <- ggplot(aes(x=Conditions, y=EEG_ITD), data=dat) + geom_boxplot()
p
p <- ggplot(aes(x=FM_avg, y=EEG_ITC), data=dat) + geom_boxplot()
p <- ggplot(aes(x=FM_avg, y=EEG_ITC), data=dat) + geom_point(size=4)
m <- lmer(EEG_ITC ~ Conditions + FM_avg + Conditions:FM_avg + (1|Subject), data = dat)
Anova(m, test.statistic = 'F')
m <- lm(EEG_ITC ~ Conditions + ITD_avg + Conditions:ITD_avg, data = dat)
Anova(m)
m <- lm(EEG_ITC ~ Conditions + ITD_avg + Conditions:ITD_avg + Error(Subject), data = dat)
m <- lm(EEG_ITC ~ Conditions + ITD_avg + Conditions:ITD_avg + error(Subject), data = dat)
m <- aov(EEG_ITC ~ Conditions + ITD_avg + Conditions:ITD_avg + Error(Subject), data = dat)
summary(m)
m <- lmer(EEG_ITC ~ Conditions + ITD_avg + Conditions:ITD_avg + (1|Subject), data = dat)
Anova(m, test.statistic = 'F')
p <- ggplot(aes(x=Conditions, y=EEG_ITC), data=dat) + geom_boxplot()
p
m <- lmer(EEG_ITC ~ ITD_avg + (1|Subject), data = dat[dat$Conditions == 180,])
m <- lm(EEG_ITC ~ ITD_avg, data = dat[dat$Conditions == 180,])
Anova(m)
m <- lm(EEG_ITC ~ ITD_avg, data = dat[dat$Conditions == 60,])
Anova(m)
m <- lmer(EEG_ITC ~ Conditions + ITD_avg + Conditions:ITD_avg + (1|Subject), data = dat[dat$Conditions != 540,])
Anova(m, test.statistic = 'F')
m <- lmer(EEG_ITC ~ Conditions + ITD_avg + (1|Subject), data = dat[dat$Conditions != 540,])
m <- lmer(EEG_ITC ~ Conditions + ITD_avg + (1|Subject), data = dat[dat$Conditions == 60 | dat$Conditions == 180,])
p <- ggplot(aes(x=ITD_avg, y=EEG_ITC), data=dat[dat$Conditions == 60 | dat$Conditions == 180,]) + geom_point(size=4)